### ISSUE TITLE
FlingListener already set

### ISSUE THREAD

**Issue by giampa-cz** [akexorcist/SnapTimePicker#6]
Hi thanks for your library, I'm using it on Java. If I open the dialog, set the time and reopen it I get:

java.lang.IllegalStateException: **An instance of OnFlingListener already set.**
        at androidx.recyclerview.widget.SnapHelper.setupCallbacks(SnapHelper.java:113)
        at androidx.recyclerview.widget.SnapHelper.attachToRecyclerView(SnapHelper.java:101)
        at com.akexorcist.snaptimepicker.SnapTimePickerDialog.prepare(SnapTimePickerDialog.kt:104)
        at com.akexorcist.snaptimepicker.BaseSnapTimePickerDialogFragment.onActivityCreated(BaseSnapTimePickerDialogFragment.kt:44)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2461)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:908)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1229)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1295)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:686)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2057)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1847)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1802)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1709)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:147)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

Here my use case (inside a fragment)

        SnapTimePickerDialog picker = new SnapTimePickerDialog.Builder()
                .setPreselectedTime(new TimeValue(calendar.get(Calendar.HOUR_OF_DAY), calendar.get(Calendar.MINUTE)))
                .build();

        picker.setListener((hourOfDay, minute) -> {
             [...]
        }
        picker.show(getFragmentManager(), TAG);

Any help would be appreciated. Please ask me if additional info are needed. Thanks again.

**Comment by akexorcist** [comment]
You have to create new `SnapTimePickerDialog` instance every time.
